// Real-world integration example for mini-trantor Task-08.
//
// Build note:
//   - This file is dependency-gated so it can live in the repo directly.
//   - Enable sections only when generated schema headers exist.
//   - See examples/codec_integration/README.md for generation and CMake wiring.

#include <cstdint>
#include <functional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "mini/codec/FlatBuffersAdapter.h"
#include "mini/codec/ProtobufAdapter.h"
#include "mini/net/broadcast/BroadcastDispatcher.h"
#include "mini/net/broadcast/BroadcastRouter.h"
#include "mini/rpc/RpcChannel.h"

#if defined(__has_include)
#    if __has_include("generated/game_message.pb.h")
#        include "generated/game_message.pb.h"
#        define MINI_TASK08_HAS_PROTO 1
#    elif __has_include("examples/codec_integration/generated/game_message.pb.h")
#        include "examples/codec_integration/generated/game_message.pb.h"
#        define MINI_TASK08_HAS_PROTO 1
#    elif __has_include("game_message.pb.h")
#        include "game_message.pb.h"
#        define MINI_TASK08_HAS_PROTO 1
#    endif

#    if __has_include("generated/game_message_generated.h")
#        include <flatbuffers/flatbuffers.h>
#        include "generated/game_message_generated.h"
#        define MINI_TASK08_HAS_FLATBUFFERS 1
#    elif __has_include("examples/codec_integration/generated/game_message_generated.h")
#        include <flatbuffers/flatbuffers.h>
#        include "examples/codec_integration/generated/game_message_generated.h"
#        define MINI_TASK08_HAS_FLATBUFFERS 1
#    elif __has_include("game_message_generated.h")
#        include <flatbuffers/flatbuffers.h>
#        include "game_message_generated.h"
#        define MINI_TASK08_HAS_FLATBUFFERS 1
#    endif
#endif

namespace example::codec {

struct GameState {
    std::uint32_t version{1};
    std::uint64_t playerId{0};
    std::string action;
    float x{0.0f};
    float y{0.0f};
    float z{0.0f};
    std::int32_t hp{100};
};

// ---------------- Protobuf integration ----------------
#if defined(MINI_TASK08_HAS_PROTO)
class GameProtoCodec : public mini::codec::ProtobufAdapter<game::protocol::GameMessage> {
public:
    // `game::protocol::GameMessage` is generated by protoc from game_message.proto.
};

inline void sendGameMoveViaRpc(mini::rpc::RpcChannel& rpc,
                              const mini::net::TcpConnectionPtr& conn,
                              const game::protocol::GameMessage& payload,
                              mini::rpc::RpcResponseCallback cb) {
    static const GameProtoCodec codec;
    static constexpr std::string_view method = "Game.Move";
    rpc.sendRequest(conn, method, payload, codec, std::move(cb), 500);
}

inline bool decodeGameMoveOnServer(std::string_view payload,
                                  game::protocol::GameMessage& out,
                                  std::string& err) {
    static const GameProtoCodec codec;
    return codec.decodeMessage(payload, out, &err);
}
#endif  // MINI_TASK08_HAS_PROTO

// ---------------- FlatBuffers integration ----------------
struct FlatGameState {
    std::uint32_t version{1};
    std::uint64_t playerId{0};
    std::string action;
    float x{0.0f};
    float y{0.0f};
    float z{0.0f};
    std::int32_t hp{100};
};

#if defined(MINI_TASK08_HAS_FLATBUFFERS)
namespace {

bool encodeFlatGame(const FlatGameState& msg, std::string* payload) {
    if (payload == nullptr) {
        return false;
    }

    flatbuffers::FlatBufferBuilder builder;
    const auto fbAction = builder.CreateString(msg.action);
    const auto fbMsg = game::protocol::CreateGameMessage(
        builder,
        msg.version,
        msg.playerId,
        msg.x,
        msg.y,
        msg.z,
        fbAction,
        msg.hp);

    builder.Finish(fbMsg, game::protocol::GameMessageIdentifier());
    payload->assign(reinterpret_cast<const char*>(builder.GetBufferPointer()),
                   builder.GetSize());
    return true;
}

bool decodeFlatGame(std::string_view payload, FlatGameState& out) {
    if (payload.empty()) {
        return false;
    }

    const auto* buffer = reinterpret_cast<const std::uint8_t*>(payload.data());
    flatbuffers::Verifier verifier(buffer, payload.size());
    if (!game::protocol::VerifyGameMessageBuffer(verifier)) {
        return false;
    }

    const auto* msg = game::protocol::GetGameMessage(buffer);
    if (msg == nullptr || msg->action() == nullptr) {
        return false;
    }

    out.version = msg->version();
    out.playerId = msg->player_id();
    out.action = msg->action()->str();
    out.x = msg->x();
    out.y = msg->y();
    out.z = msg->z();
    out.hp = msg->hp();
    return true;
}

const mini::codec::FlatBuffersAdapter<FlatGameState>& flatGameCodec() {
    static const mini::codec::FlatBuffersAdapter<FlatGameState> codec(
        [](const FlatGameState& msg, std::string* payload) { return encodeFlatGame(msg, payload); },
        [](std::string_view data, FlatGameState& out) { return decodeFlatGame(data, out); });
    return codec;
}

}  // namespace

inline void sendGameStateBroadcast(mini::net::broadcast::BroadcastDispatcher& dispatcher,
                                  std::vector<mini::net::broadcast::BroadcastRouter::LoopBatch> batches,
                                  const FlatGameState& state,
                                  std::string* err) {
    dispatcher.dispatch(std::move(batches), state, flatGameCodec(), err);
}

inline bool encodeGameStatePayload(const FlatGameState& state,
                                  std::string& payload,
                                  std::string* err = nullptr) {
    return flatGameCodec().encodeMessage(state, &payload, err);
}

inline bool decodeGameStateOnServer(std::string_view payload,
                                   FlatGameState& out,
                                   std::string& err) {
    return flatGameCodec().decodeMessage(payload, out, &err);
}
#endif  // MINI_TASK08_HAS_FLATBUFFERS

}  // namespace example::codec
