#include "mini/net/TlsContext.h"

#include <cassert>
#include <cstdio>
#include <stdexcept>
#include <string>

using namespace mini::net;

namespace {

// Test certs are generated by tests/certs/generate_test_certs.sh
// relative to the test binary's working directory (build dir)
const std::string kCertDir = SOURCE_DIR "/tests/certs/";
const std::string kServerCert = kCertDir + "server.crt";
const std::string kServerKey = kCertDir + "server.key";
const std::string kCaCert = kCertDir + "ca.crt";

void testServerContextCreation() {
    auto ctx = TlsContext::newServerContext(kServerCert, kServerKey);
    assert(ctx != nullptr);
    assert(ctx->nativeHandle() != nullptr);
    std::printf("  PASS: testServerContextCreation\n");
}

void testClientContextCreation() {
    auto ctx = TlsContext::newClientContext();
    assert(ctx != nullptr);
    assert(ctx->nativeHandle() != nullptr);
    std::printf("  PASS: testClientContextCreation\n");
}

void testServerContextInvalidCert() {
    bool thrown = false;
    try {
        TlsContext::newServerContext("/nonexistent/cert.pem", "/nonexistent/key.pem");
    } catch (const std::runtime_error&) {
        thrown = true;
    }
    assert(thrown);
    std::printf("  PASS: testServerContextInvalidCert\n");
}

void testServerContextMismatchedKey() {
    // Using CA cert with server key should fail key check
    bool thrown = false;
    try {
        TlsContext::newServerContext(kCaCert, kServerKey);
    } catch (const std::runtime_error&) {
        thrown = true;
    }
    assert(thrown);
    std::printf("  PASS: testServerContextMismatchedKey\n");
}

void testSetCaCertPath() {
    auto ctx = TlsContext::newClientContext();
    ctx->setCaCertPath(kCaCert);
    std::printf("  PASS: testSetCaCertPath\n");
}

void testSetCaCertPathInvalid() {
    auto ctx = TlsContext::newClientContext();
    bool thrown = false;
    try {
        ctx->setCaCertPath("/nonexistent/ca.pem");
    } catch (const std::runtime_error&) {
        thrown = true;
    }
    assert(thrown);
    std::printf("  PASS: testSetCaCertPathInvalid\n");
}

void testSetVerifyPeer() {
    auto ctx = TlsContext::newClientContext();
    ctx->setVerifyPeer(true);
    ctx->setVerifyPeer(false);
    std::printf("  PASS: testSetVerifyPeer\n");
}

void testContextSharedOwnership() {
    auto ctx = TlsContext::newClientContext();
    auto ctx2 = ctx;
    assert(ctx.use_count() == 2);
    ctx2.reset();
    assert(ctx.use_count() == 1);
    assert(ctx->nativeHandle() != nullptr);
    std::printf("  PASS: testContextSharedOwnership\n");
}

}  // namespace

int main() {
    std::printf("=== TlsContext Unit Tests ===\n");
    testServerContextCreation();
    testClientContextCreation();
    testServerContextInvalidCert();
    testServerContextMismatchedKey();
    testSetCaCertPath();
    testSetCaCertPathInvalid();
    testSetVerifyPeer();
    testContextSharedOwnership();
    std::printf("All TlsContext unit tests passed.\n");
    return 0;
}
